### ISSUE TITLE
Issue with autoloading rules

### ISSUE THREAD

**Issue by xaoc2** [Nordeus/ansible_iptables_raw#9]
Hi! Loading at boot is not working on Ubuntu Xenial, even with iptables-persistent package installed before running iptables_raw playbook. Info about autoload rules at boot Debian-like distros I have read here http://blog.nordeus.com/files/libraryblog/articles/managing-iptables-with-ansible/iptables_raw.html

**Comment by kustodian** [comment]
Could you please check if `netfilter-persistent` service is enabled? You can check with the following command:
```
sudo systemctl is-enabled netfilter-persistent
```
and if it's disabled you can enabled it with:
```
sudo systemctl enable netfilter-persistent
```

**Comment by xaoc2** [comment]
# systemctl is-enabled netfilter-persistent
enabled

So, iptables-persistent is enabled, I am running the playbook with iptables rules and the rules are not loading after reboot

**Comment by kustodian** [comment]
Can you see the rules being saved in `/etc/iptables/rules.v4`? Can you run `sudo cat /etc/iptables/rules.v4`? Does it print the rules?

**Comment by xaoc2** [comment]
I've updated the module and this issue has gone.

**Comment by kustodian** [comment]
The first version of the module didn't support Debian based distributions, it was added a little bit later. Glad that it is resolved and thanks for using the module :)
